[pytest]
testpaths = tests
pythonpath = packages src
cache_dir = target/.pytest_cache
addopts = --cov=addon_updater
          --cov-report=xml:coverage.xml
          --cov-report=html:target/htmlcov
          --cov-report=term-missing
          -v
